### ISSUE TITLE
py.typed location

### ISSUE THREAD

**Issue by layday** [pycontribs/ruyaml#11]
The `py.typed` marker file should be placed in the package folder, not in the project root.

**Comment by layday** [comment]
This should've been moved into the 'yaml' folder (not 'ruamel') since we can't guarantee that the entire [ruamel](https://pypi.org/search/?q=ruamel) namespace is typed.  PEP 561 says:

> For namespace packages (see PEP 420), the `py.typed` file should be in the submodules of the namespace, to avoid conflicts and for clarity.

**Comment by ssbarnea** [comment]
Do you know a command that we can use to validate correct typing information?

**Comment by ssbarnea** [comment]
@layday Please review the linked PR. I also sent you an invite to the repository.

**Comment by layday** [comment]
> Do you know a command that we can use to validate correct typing information?

Afraid not, sorry.  Thank you for the invite :)
