### ISSUE TITLE
Remove usages of ruamel.ordereddict, ruamel.std.argparse, and ruamel.std.pathlib

### ISSUE THREAD

**Issue by jwilson8767** [pycontribs/ruyaml#15]
I think these three were just for backwards compatibility, so when we eventually remove Python 2 support I think we can remove these dependencies as well.

**Comment by ssbarnea** [comment]
A PR would be more than welcomed.

**Comment by ssbarnea** [comment]
Fixed yesterday, we no longer depend on any of these.
