### ISSUE TITLE
Attempting uninstall: ruamel.yaml

### ISSUE THREAD

**Issue by kaiyungtan** [pycontribs/ruyaml#49]
Hi ,

When I was trying to install great_expectation on terminal, I got this error:

Installing collected packages: ruamel.yaml, jsonpatch, altair, great-expectations
  Attempting uninstall: ruamel.yaml
    Found existing installation: ruamel-yaml 0.15.87
ERROR: Cannot uninstall 'ruamel-yaml'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

any suggestions to solve this issue?

many thanks

**Comment by smurfix** [comment]
Create a venv for your project? Clean out and reinstall Python?

Which OS? Presumably not Linux …

**Comment by kaiyungtan** [comment]
Hi , I managed to install great expectations after create a venv for my project. thanks
