### ISSUE TITLE
linters test case is failing

### ISSUE THREAD

**Issue by dthadi3** [pycontribs/ruyaml#51]
Hi guys,
can anyone help me out from this linters test case issue.....
It's failing for intel as we as power too, Below is the URL for reference
https://travis-ci.com/github/dthadi3/ruyaml/builds/220072931

**Comment by dthadi3** [comment]
[INFO] This may take a few minutes...
isort....................................................................Passed
black....................................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook
Fixing .travis.yml
Mixed line ending........................................................Passed
check BOM - deprecated: use fix-byte-order-marker........................Passed
Check that executables have shebangs.................(no files to check)Skipped
Check for merge conflicts................................................Passed
Debug Statements (Python)................................................Passed
flake8...................................................................Passed
mypy.....................................................................Passed
ERROR: InvocationError for command /home/travis/build/dthadi3/ruyaml/.tox/linters/bin/pre-commit run -a (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   linters: commands failed
The command "tox" exited with 1.

**Comment by grahamgower** [comment]
From the log, I'm guessing the `.travis.yml` file has trailing whitespace in it.
```
Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook
Fixing .travis.yml
```

Probably you should install and run `pre-commit` in your local repository.

**Comment by smurfix** [comment]
We should probably replace Travis with Github anyway …

**Comment by grahamgower** [comment]
> We should probably replace Travis with Github anyway …

Umm... you already have? The Travis config file is in @dthadi3's fork.

**Comment by ssbarnea** [comment]
Fixed on master
