### ISSUE TITLE
Latest versions of the package not available in pypi

### ISSUE THREAD

**Issue by muripic** [pycontribs/ruyaml#58]
We're using ruyaml in [yamlfix](https://github.com/lyz-code/yamlfix) and we need to update the dependencies with the latest version to include [this fix](https://github.com/pycontribs/ruyaml/commit/1be1a708aaeffc55271d9c86ff56a59c14de4556). However, the [latest version available is 0.20.0](https://pypi.org/project/ruyaml/), which appears to be inconsistent with the tags in the repository.

Maybe I'm missing something and there's a good reason for this, but I just wanted to point out that it'd be great to have the package available in pypi since it's such a useful great project :smiley:

**Comment by lyz-code** [comment]
Hi @ssbarnea, sorry to ping you again :(,  does @muripic message solve your question?  

We've got the builds of [yamlfix](https://github.com/lyz-code/yamlfix) broken until you release the fix in Pypi

**Comment by ssbarnea** [comment]
@lyz-code Thanks for pinging me. I really need someone that can take care of this repo maintenance. Pipelines were disabled for not running for a long time for exampel.

**Comment by lyz-code** [comment]
@muripic and I can help to bring the pipelines back to life at least, but I guess we'll need some permissions and maybe credentials to push to Pypi

**Comment by gdubicki** [comment]
@ssbarnea I can also help. :)

**Comment by ssbarnea** [comment]
@gdubicki @lyz-code Please check your email. I sent you invites!

**Comment by muripic** [comment]
@lyz-code @ssbarnea I'll be super happy to help :)
I've been beyond busy these past few weeks but in about two weeks from now I will have time to contribute!

**Comment by ssbarnea** [comment]
I published current code as a pre-release, please test it well and post on https://github.com/pycontribs/ruyaml/discussions/75 if you think it is ok to release it or not.
