### ISSUE TITLE
Please remove 1.0.0.a0 from Pypi

### ISSUE THREAD

**Issue by lyz-code** [pycontribs/ruyaml#97]
Hi, I've started allowing pre-releases in my package manager to early catch issues with the dependencies I use and help their developers.

When I've enabled them for [`yamlfix`](https://github.com/lyz-code/yamlfix) it installs the version `1.0.0.a0` of `ruyaml` which returns some issues with anchors.

From what [I see from Pypi](https://pypi.org/project/ruyaml/#history) the pre-release was made on Dec 16 of 2020, and the latest stable version is of Dec 7 of 2021, which makes me think that the version is outdated. If it is, I'd be glad if you could remove the version from Pypi so I can catch your possible pre-releases

**Comment by ssbarnea** [comment]
I removed it even if it was not really needed. I think that is more of a poetry issue than anything else.
